networks:
    net:
        name: net
        external: true  # Создается в docker-compose.db.yaml

services:
    recruitai-vacancy:
        build:
            context: "../../${RECRUITAI_VACANCY_CONTAINER_NAME}"
            dockerfile: "${RECRUITAI_VACANCY_DOCKERFILE_DIR}/Dockerfile"
        container_name: "${RECRUITAI_VACANCY_CONTAINER_NAME}"
        env_file:
            - "../env/.env.app"
            - "../env/.env.db"
            - "../env/.env.monitoring"
        ports:
            - "${RECRUITAI_VACANCY_PORT}:${RECRUITAI_VACANCY_PORT}"
        restart: unless-stopped
        networks:
            - net

    recruitai-frontend:
        build:
            context: "../../${RECRUITAI_FRONTEND_CONTAINER_NAME}"
            dockerfile: "Dockerfile"
        container_name: "${RECRUITAI_FRONTEND_CONTAINER_NAME}"
        env_file:
            - "../env/.env.app"
        ports:
            - "${RECRUITAI_FRONTEND_PORT}:${RECRUITAI_FRONTEND_PORT}"
        restart: unless-stopped
        networks:
            - net